main: iomatix.spigot.rpgleveledmobs.Main
softdepend: [MobArena, Heroes, LegendQuest, SkillAPI, Vault, Towny]
load: POSTWORLD
name: RPGLeveledMobs
version: 2.6.8
api-version: 1.14
author: iomatix
description: Leveled mobs with scaling attributes compatible with many RPG plugins.
commands:
  rpgmobs:
    description: RPG Level Mobs command prefix.
    permission: rpgleveledmobs.admin
    permission-message: You do not have rpgleveledmobs permission to use the RPGLeveledMobs plugin.